#!/usr/bin/env python3
"""Build CATALOG.md: every openai/math manuscript, grouped by discipline and family.

Each manuscript maps to one directory, papers/<preprint-slug>/, using the same
slug as openai/math/preprints/<preprint-slug>/. A paper counts as explained
once papers/<preprint-slug>/README.md is tracked by git (so drafts in progress
are not linked); outside a git checkout, existence on disk is used instead.

Usage:
    curl -sLO https://raw.githubusercontent.com/openai/math/main/CONTENTS.md
    curl -sLO https://raw.githubusercontent.com/openai/math/main/overview.tex
    python3 scripts/build_catalog.py CONTENTS.md overview.tex > CATALOG.md
"""

import re
import subprocess
import sys
from collections import OrderedDict
from pathlib import Path

UPSTREAM = "https://github.com/openai/math/blob/main/"
REPO_ROOT = Path(__file__).resolve().parent.parent

FAMILY_RE = re.compile(r"^\*\*(\d{3})\. (.+?)\*\*\s*(.*)$")
PAPER_RE = re.compile(r"^&emsp;\[(.*)\]\((preprints/([^/]+)/[^)]+)\)\s*(.*)$")
SECTION_RE = re.compile(r"\\cataloguesection\{([^}]*)\}")
ENTRY_RE = re.compile(r"\\resultentry\{(\d{3})\}")


def parse_disciplines(overview_tex):
    """Map family number -> discipline, in catalogue order."""
    disciplines = OrderedDict()
    current = None
    for line in overview_tex.splitlines():
        section = SECTION_RE.search(line)
        if section:
            current = section.group(1)
            disciplines.setdefault(current, [])
        entry = ENTRY_RE.search(line)
        if entry and current:
            disciplines[current].append(entry.group(1))
    return disciplines


def parse_families(contents_md):
    """Map family number -> {title, papers: [(title, upstream_path, slug)]}."""
    families = OrderedDict()
    current = None
    for line in contents_md.splitlines():
        family = FAMILY_RE.match(line)
        if family:
            number, title, _ = family.groups()
            current = families.setdefault(number, {"title": title.rstrip("."), "papers": []})
            continue
        paper = PAPER_RE.match(line)
        if paper and current is not None:
            title, path, slug, note = paper.groups()
            title = title.strip()
            if note.strip():
                # e.g. "— secondary writeup"
                title = f"{title} _{note.strip()}_"
            current["papers"].append((title, path, slug))
    return families


def cell(text):
    """Escape pipes so titles with |x| do not break the table."""
    return text.replace("|", "\\|")


def explained_slugs():
    """Slugs whose explainer README is tracked by git (or on disk without git)."""
    try:
        out = subprocess.run(
            ["git", "-C", str(REPO_ROOT), "ls-files", "papers/*/README.md"],
            check=True, capture_output=True, text=True,
        ).stdout
        return {Path(line).parts[1] for line in out.splitlines() if line}
    except (OSError, subprocess.CalledProcessError):
        return {p.parent.name for p in (REPO_ROOT / "papers").glob("*/README.md")}


EXPLAINED = explained_slugs()


def status_cell(slug):
    if slug in EXPLAINED:
        return f"✅ [read the explainer](papers/{slug}/)"
    return "⬜ not yet"


def main():
    contents_md = Path(sys.argv[1]).read_text(encoding="utf-8")
    overview_tex = Path(sys.argv[2]).read_text(encoding="utf-8")
    families = parse_families(contents_md)
    disciplines = parse_disciplines(overview_tex)

    # Families missing from the overview still get listed.
    listed = {n for numbers in disciplines.values() for n in numbers}
    unlisted = [n for n in families if n not in listed]
    if unlisted:
        disciplines["Other"] = unlisted

    total_papers = sum(len(f["papers"]) for f in families.values())
    explained = sum(1 for f in families.values() for _, _, slug in f["papers"] if slug in EXPLAINED)

    out = []
    out.append("# Catalogue of papers")
    out.append("")
    out.append(
        f"Every manuscript in [openai/math](https://github.com/openai/math): "
        f"**{total_papers} papers in {len(families)} result families**. "
        f"**{explained}** explained so far."
    )
    out.append("")
    out.append(
        "Each paper gets its own directory, `papers/<preprint-slug>/`, named exactly like "
        "`openai/math/preprints/<preprint-slug>/`. Families and disciplines follow the "
        "openai/math [overview](https://github.com/openai/math/blob/main/overview.pdf)."
    )
    out.append("")
    out.append("_Generated by `scripts/build_catalog.py`. Do not edit by hand._")
    out.append("")
    out.append("## Disciplines")
    out.append("")
    for name, numbers in disciplines.items():
        anchor = re.sub(r"[^a-z0-9 -]", "", name.lower()).replace(" ", "-")
        count = sum(len(families[n]["papers"]) for n in numbers if n in families)
        out.append(f"- [{name}](#{anchor}): {len(numbers)} families, {count} papers")
    out.append("")

    for name, numbers in disciplines.items():
        out.append(f"## {name}")
        out.append("")
        out.append("| Family | Paper (openai/math) | Explainer |")
        out.append("|---|---|---|")
        for number in numbers:
            family = families.get(number)
            if not family:
                continue
            for i, (title, path, slug) in enumerate(family["papers"]):
                family_cell = f"**{number}** {cell(family['title'])}" if i == 0 else "↳"
                out.append(f"| {family_cell} | [{cell(title)}]({UPSTREAM}{path}) | {status_cell(slug)} |")
        out.append("")

    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
