#!/usr/bin/env python3
"""Render NotebookLM mind-map JSON files as nested Markdown lists.

Usage:
    python3 scripts/mindmap_to_markdown.py "Title A" a.json "Title B" b.json > mindmaps.md
"""

import json
import sys
from pathlib import Path


def render(node, depth, out):
    name = node.get("name", "").strip()
    if depth == 0:
        out.append(f"**{name}**")
        out.append("")
    else:
        out.append(f"{'  ' * (depth - 1)}- {name}")
    for child in node.get("children", []):
        render(child, depth + 1, out)


def load(path):
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    # `nlm download mind-map` may wrap the tree; unwrap a JSON string if needed.
    if isinstance(data, dict) and "mind_map_json" in data:
        data = json.loads(data["mind_map_json"])
    return data


def main():
    args = sys.argv[1:]
    if not args or len(args) % 2:
        sys.exit(__doc__)
    out = ["# Mind maps", "", "Generated by NotebookLM and rendered as nested lists. Raw JSON files sit next to this page.", ""]
    for title, path in zip(args[::2], args[1::2]):
        out.append(f"## {title}")
        out.append("")
        render(load(path), 0, out)
        out.append("")
        out.append(f"_Source: [`{Path(path).name}`]({Path(path).name})_")
        out.append("")
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
